### ISSUE TITLE
cast_storage (csr->dense) segfault when total number of elements is greater than 2 billion

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/mxnet#103]

**Comment by eric-haibin-lin** [comment]
https://github.com/eric-haibin-lin/mxnet/blob/master/src/operator/nn/cast_storage-inl.h#L234
this not big enough, since the CSR matrix could have billions of rows. We need to test large inputs now..
@reminisce

**Comment by reminisce** [comment]
This was developed before the nnvm TShape dim size change. I will change those ints to size_t later.

BTW, you meant a csr matrix could have billions of columns, rather than rows, right?

**Comment by eric-haibin-lin** [comment]
oh yes columns. thats a typo. `size_t` doesn't guarantee 64 bit. better use int64_t

**Comment by reminisce** [comment]
Got it.
