### ISSUE TITLE
why label_libsvm in iter_libsvm.cc is needed?

### ISSUE THREAD

**Issue by CNevd** [eric-haibin-lin/mxnet#117]
why not just use the label in data_libsvm since libsvm data always put label and data together?
and if so we can read the dataset in a distributed way, says different workers load different part of the dataset from such as HDFS :)

**Comment by eric-haibin-lin** [comment]
if `label_path` is Null, the labels are read from `data_path`. The option is used for use cases where the output labels are sparse matrices, too
