### ISSUE TITLE
Communication Cost

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/mxnet#13]
Communication cost of data parallel. 
seq len = 1, batch size = 32. 

| #GPU | Sec per epoch |
| --- | --- |
| 1 | 97 |
| 2 | 127 |
| 3 | 142 |
| 4 | 177 |

<img width="538" alt="screen shot 2016-05-07 at 1 32 31 am" src="https://cloud.githubusercontent.com/assets/5545640/15090352/ad9ff99c-13f3-11e6-8015-24bdeb0556fc.png">

**Comment by harouwu** [comment]
MP: 8 layers, hidden:400 embeded: 200
no kvstore, len = 1, batch_size = 32
| #GPU | Sec per epoch 
| --- | --- | 
| 1 | 50.669 |
| 2 | 40.777 |
| 3 | 37.951 |
| 4 | 39.219 |

**Comment by eric-haibin-lin** [comment]
3, 
4, 145

**Comment by eric-haibin-lin** [comment]
DP: 8 layers, hidden:400 embeded: 200
batch_size = 32, bucket = [10,20,30,40,50,60]

| #GPU | Sec per epoch 
| --- | --- | 
1 | 260
2 |  
3 |  
4 |
