### ISSUE TITLE
MP > DP experiment

### ISSUE THREAD

**Issue by harouwu** [eric-haibin-lin/mxnet#14]
DP [10-60], 32, 8 layer, 400 200

| #GPU | Sec per epoch |
| --- | --- |
| 1 | 300.412 |
| 2 | 336.081 |
| 3 | 377.795 |
| 4 | 412.7 |

MP [10-60], 32, 8 layer, 400 200

| #GPU | Sec per epoch |
| --- | --- |
| 1 | 336.121 |
| 2 | 219.809 |
| 3 | 182.0 |
| 4 | 164.9 |

**Comment by harouwu** [comment]
|  | Triplet | AlexNet+Euclidean | AlexNet + Cosine
| --- | --- | --- | --- |
| Coarse | 0.75814 | 0.27342 | 0.28571 |
| Fine-grained | 0.80465 | 0.43965 | 0.44453 |

FG: 8599 query sets;
Coarse: 3009 query sets

**Comment by eric-haibin-lin** [comment]
Speedup of Model Parallel and Data Parallel 

DP [10-60], 32, 8 layer, 400 200


<img width="546" alt="screen shot 2016-05-06 at 8 24 25 pm" src="https://cloud.githubusercontent.com/assets/5545640/15088982/9b412454-13c8-11e6-928e-a37e93a2b888.png">

**Comment by eric-haibin-lin** [comment]
<img width="530" alt="screen shot 2016-05-06 at 8 46 45 pm" src="https://cloud.githubusercontent.com/assets/5545640/15089163/ba2efb72-13cb-11e6-82b6-69e437d6dc3a.png">

**Comment by eric-haibin-lin** [comment]
I realized that in the DP experiment, we didn't scale `batch_size` with the number of GPUs :(
