### ISSUE TITLE
[proposal] new infer_storage_type interface 

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/mxnet#158]
####  Background:
The current rule for graph executor to dispatch on `FCompute` & `FComputeEx` is naive: if any input/output contains non-default storage, `FComputeEx` will be preferred; otherwise, choose `FCompute`. 

#### Why it's bad:
- Such dispatch rule may lead to the case where `FComputeEx` is registered and chosen to dispatch, but it's not capable of handle specific storage types, and need to fallback inside `FComputeEx`. Ideally we want `FComputeEx` functions to be fallback free. 
- Since fallback requires temp resource on gpu, when fallback happen inside `FComputeEx`, the resource need to requested on the fly. This leads to unclear responsibility since all resource requests are expected to be handled in attach_exec_resource_pass. 

#### How to fix it:
We should incorporate dispatch logic inside infer_storage_type pass with the new interface below:
```cpp
enum FcompDispatchType {
  kFCompute;
  kFComputeEx;
  kFComputeFallback;
}
inline bool InferStorageType(const nnvm::NodeAttrs& attrs,
    const Context& ctx,
    std::vector<int> *in_attrs,
    std::vector<int> *out_attrs,
    FcompDispatchType *type) {}
```
During infer_storage_type pass, we will decide whether to dispatch for FComputeEx or FCompute based on attrs. For example, if we implemented `dot(dns, dns) = dns` in `FCompute`, `dot(csr, dns) = dns` in `FComputeEx`, and didn't implement any other case, then the FInferStorageType would be:

```cpp
inline bool InferStorageType(const nnvm::NodeAttrs& attrs,
    const Context& ctx,
    std::vector<int> *in_attrs,
    std::vector<int> *out_attrs,
    FcompDispatchType *type) {
  
  if (in_attrs->at(0) == kDefaultStorage && in_attrs->at(1) == kDefaultStorage) {
    // try to assign stype to output[0]
    if (type_assign(out_attrs->at(0), kDefaultStorage)) {
        // assign successful, dispatch on `FCompute`
        *type = kFCompute;
    } else {
        // assign failure, out_attr could already be kCSRStorage or kRowSparseStorage,
        // we need to fallback.
        // choose to dispatch FCompute and FCompute Executor will handle fallback
        *type = kFComputeFallback;
    }
  } else if (in_attrs->at(0) == kCSRStorage && in_attrs->at(1) == kDefaultStorage) {
    // try to assign stype to output[0]
    if (type_assign(out_attrs->at(0), kDefaultStorage)) {
        // assign successful, dispatch on `FcomputeEx`
        *type = kFComputeEx;
    } else {
        // assign failure, out_attr could already be kCSRStorage or kRowSparseStorage, 
        // we need to fallback. 
        // Choose to dispatch FCompute and FCompute Executor will handle fallback
        *type = kFComputeFallback;
    }
  } else {
    // here means input stypes include the ones we didn't implement like dot(csr, csr).
    // definitely fallback. 
    type_assign(out_attrs->at(0), kDefaultStorage);
    *type = kFCompute; 
  }
  ...
}
```

FComputeEx interface won't change, the implementation will be sth like:
```cpp
void DotFComputeEx(...) {
   if (in_stype0 == csr && in_stype1 == dns && out_stype == dns) {
      // this is implemented
      DotFComputeCsrDnsDnsImpl(...)
   } else {
      // will never reach this line
      LOG(FATAL) << "Not reached";
   }
}

```

Changes to graph executor:
- When dispatch type is kFComputeFallback, attach extra resource for cast_storage on gpu 
- need to pass 'dispatch_storage_type' graph attr to infer_storage_pass since it stores the dispatch inference result
- (apply the same logic for ndarray imperative execution)

**Comment by eric-haibin-lin** [comment]
Update: we should include FStatefulCompute dispatch logic in this pass. 
Assumption: an operator is either stateful, or stateless. 

```
enum FcompDispatchType {
  kFCompute;   // dispatch on FCompute or FStatefulCompute
  kFComputeEx; // dispatch on FComputeEx or FStatefulComputeEx
  kFComputeFallback; // dispatch on FCompute or FStatefulCompute, and request resource for fallback
}
```
If the operator doesn't register `FInterStorageType`, the default infer_storage_type would be:
```
inline bool InferStorageType(const nnvm::NodeAttrs& attrs,
    const Context& ctx,
    std::vector<int> *in_attrs,
    std::vector<int> *out_attrs,
    FcompDispatchType *type) {
  
  bool all_dense = true;
  for (in_attr : in_attrs) {
    bool success = type_assign(in_attr, kDefaultStorage);
    all_dense = all_dense && success;
  }
  if (all_dense) *type = kFCompute;
  else *type = kFComputeFallback;

```
@reminisce @piiswrong @cjolivier01

**Comment by cjolivier01** [comment]
Does this cause the fallback to be called, or is simply used for notifying the binding that the operator may need to allocate temporary data?

**Comment by cjolivier01** [comment]
Point being, tomorrow we start supporting a new CRS storage for some operators.  Fallback will still occur on-the-fly from the operator handler or at bind time, the determination is to be made?

**Comment by eric-haibin-lin** [comment]
At bind time we'll decide if fallback will happen. There's supposed to be no fallback call inside the operator.
