### ISSUE TITLE
Week 2 issues

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/mxnet#5]
* take a look at trade off of converge rate vs. performance with different batch size
* apply bucketing to model parallelism 
* evaluate model parallelism with diff number of GPUs (can increase the number of hidden layer to increase workload) 
* evaluate model parallelism with & without auto bucketing  
* discuss bucketing implementation details with pluskid

**Comment by harouwu** [comment]
LOL I can close it now

**Comment by eric-haibin-lin** [comment]
why close it..?

**Comment by harouwu** [comment]
Because I did not read the content
