### ISSUE TITLE
Converge Picture

### ISSUE THREAD

**Issue by harouwu** [eric-haibin-lin/mxnet#8]
https://www.dropbox.com/s/okryq922s0mqhfm/gpu_1_32_.png?dl=0

https://www.dropbox.com/s/m02wiiuz0klg7cg/gpu_1_64.png?dl=0

**Comment by eric-haibin-lin** [comment]
<img width="546" alt="screen shot 2016-04-14 at 9 08 57 pm" src="https://cloud.githubusercontent.com/assets/5545640/14548483/2677ce06-0285-11e6-8cfe-24a16465119e.png">

<img width="547" alt="screen shot 2016-04-14 at 9 09 02 pm" src="https://cloud.githubusercontent.com/assets/5545640/14548485/29a94b90-0285-11e6-8364-b8f814ca043d.png">

**Comment by eric-haibin-lin** [comment]
<img width="433" alt="screen shot 2016-04-14 at 9 24 45 pm" src="https://cloud.githubusercontent.com/assets/5545640/14548692/56003346-0287-11e6-859e-8e15c4f8f458.png">

**Comment by eric-haibin-lin** [comment]
<img width="510" alt="screen shot 2016-04-14 at 10 56 11 pm" src="https://cloud.githubusercontent.com/assets/5545640/14550148/32167e10-0294-11e6-9b9f-7b87790971cc.png">
